name: Denopendabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    name: Run App
    runs-on: ubuntu-latest

    steps:
      # dispatch a `denopendabot_run` repository event
      - name: Dispatch Run
        uses: hasundue/denopendabot@0.17.2 # @denopendabot hasundue/denopendabot
        with:
          mode: app
          # or 'action' if you want run Denopendabot locally

          # branch to update dependencies
          base-branch: main

          # branch for Denopendabot to commit changes
          working-branch: denopendabot

          # labels for pull requests
          labels: dependencies

          # merge pull requests automatically if all the checks are passing
          auto-merge: any

